/**
 * Utility to sync orchestration state to activeContext.md
 */

import * as fs from 'fs';
import * as path from 'path';
import { getDatabase } from '../database.js';
import { isCursorDelegationMetadata, TaskStatus } from '../models.js';

/**
 * Check if context sync is enabled via environment variable
 */
export function isContextSyncEnabled(): boolean {
  const envVar = process.env.MCP_ORCH_SYNC_CONTEXT;
  return envVar === 'true' || envVar === '1';
}

/**
 * Get the path to activeContext.md
 */
function getContextPath(): string {
  return path.join(process.cwd(), 'activeContext.md');
}

/**
 * Sync the current orchestration state to activeContext.md
 */
export function syncToActiveContext(): void {
  if (!isContextSyncEnabled()) {
    return;
  }

  try {
    const db = getDatabase();

    // Cleanup stale agents so the file reflects reality
    db.cleanupStaleAgents();

    // Get current state
    const agents = db.listAgents();
    const activeAgents = agents.filter((a) => ['active', 'busy'].includes(a.status));
    const inProgressTasks = db.listTasks({ status: TaskStatus.IN_PROGRESS });
    const pendingTasks = db.listTasks({ status: TaskStatus.PENDING });
    const delegatedTasks = db
      .listTasks()
      .filter((task) => isCursorDelegationMetadata(task.metadata));
    const decisions = db.listMemory('decisions');
    const context = db.listMemory('context');

    // Get current focus
    const focusEntry = db.getMemory('current_focus', 'context');
    const currentFocus = focusEntry
      ? String(focusEntry.value)
      : '_Not set. Use `memory_set` with key "current_focus" in namespace "context"._';

    // Build markdown content
    const lines: string[] = [
      '# Active Context',
      '',
      `_Last updated: ${new Date().toISOString()}_`,
      '',
      '## Current Focus',
      '',
      currentFocus,
      '',
      '## Active Agents',
      '',
    ];

    if (activeAgents.length === 0) {
      lines.push('_No active agents._');
    } else {
      for (const agent of activeAgents) {
        const statusEmoji = agent.status === 'busy' ? '🔵' : '🟢';
        lines.push(`- ${statusEmoji} **${agent.name}** (${agent.role})`);
      }
    }

    lines.push('', '## In Progress', '');

    if (inProgressTasks.length === 0) {
      lines.push('_No tasks in progress._');
    } else {
      for (const task of inProgressTasks) {
        const progress = (task.metadata.progress as number) ?? 0;
        const assignee = task.assignedTo
          ? agents.find((a) => a.id === task.assignedTo)?.name ?? task.assignedTo.slice(0, 8)
          : 'unassigned';
        lines.push(`- 🔄 **${task.title}** - ${assignee} (${progress}%)`);
      }
    }

    lines.push('', '## Pending Tasks', '');

    if (pendingTasks.length === 0) {
      lines.push('_No pending tasks._');
    } else {
      for (const task of pendingTasks.slice(0, 10)) {
        const priority = task.priority !== 'normal' ? ` [${task.priority}]` : '';
        lines.push(`- ⏳ ${task.title}${priority}`);
      }
      if (pendingTasks.length > 10) {
        lines.push(`- _...and ${pendingTasks.length - 10} more_`);
      }
    }

    lines.push('', '## Cursor Delegations', '');

    if (delegatedTasks.length === 0) {
      lines.push('_No Cursor delegations._');
    } else {
      for (const task of delegatedTasks.slice(0, 10)) {
        const metadata = task.metadata;
        if (!isCursorDelegationMetadata(metadata)) {
          continue;
        }

        const mode = metadata.providerMode ?? 'agent';
        const chatId = metadata.providerChatId ?? 'n/a';
        lines.push(`- 🤖 **${task.title}** - ${metadata.providerStatus} via ${mode} (chat: ${chatId})`);
      }
    }

    lines.push('', '## Recent Decisions', '');

    if (decisions.length === 0) {
      lines.push('_No decisions recorded._');
    } else {
      for (const decision of decisions.slice(0, 10)) {
        const value =
          typeof decision.value === 'string'
            ? decision.value.slice(0, 100)
            : JSON.stringify(decision.value).slice(0, 100);
        lines.push(`- **${decision.key}**: ${value}`);
      }
    }

    lines.push('', '## Context Notes', '');

    const otherContext = context.filter((c) => c.key !== 'current_focus');
    if (otherContext.length === 0) {
      lines.push('_No additional context._');
    } else {
      for (const entry of otherContext.slice(0, 10)) {
        const value =
          typeof entry.value === 'string'
            ? entry.value.slice(0, 80)
            : JSON.stringify(entry.value).slice(0, 80);
        lines.push(`- **${entry.key}**: ${value}`);
      }
    }

    lines.push(
      '',
      '---',
      '',
      '_This file is auto-generated by the Agent Orchestration server._',
      '_Edit shared memory to update this context._'
    );

    // Write to file
    fs.writeFileSync(getContextPath(), lines.join('\n'), 'utf-8');
  } catch (error) {
    // Silently fail - this is a nice-to-have feature
    console.error('Failed to sync activeContext.md:', error);
  }
}
